namespace BingApisLib.BingMapsRestApi
{
    using System.Runtime.Serialization;

    /// <summary>
    /// http://msdn.microsoft.com/en-us/library/gg650392.aspx
    /// </summary>
    [DataContract(Name = "ManeuverType")]
    public enum ManeuverType
    {
        [EnumMember]
        ArriveFinish,
        [EnumMember]
        ArriveIntermediate,
        [EnumMember]
        BearLeft,
        [EnumMember]
        BearLeftThenBearLeft,
        [EnumMember]
        BearLeftThenBearRight,
        [EnumMember]
        BearLeftThenTurnLeft,
        [EnumMember]
        BearLeftThenTurnRight,
        [EnumMember]
        BearRight,
        [EnumMember]
        BearRightThenBearLeft,
        [EnumMember]
        BearRightThenBearRight,
        [EnumMember]
        BearRightThenTurnLeft,
        [EnumMember]
        BearRightThenTurnRight,
        [EnumMember]
        BearThenKeep,
        [EnumMember]
        BearThenMerge,
        [EnumMember]
        Continue,
        [EnumMember]
        DepartIntermediateStop,
        [EnumMember]
        DepartIntermediateStopReturning,
        [EnumMember]
        DepartStart,
        [EnumMember]
        EnterRoundabout,
        [EnumMember]
        ExitRoundabout,
        [EnumMember]
        EnterThenExitRoundabout,
        [EnumMember]
        KeepLeft,
        [EnumMember]
        KeepOnRampLeft,
        [EnumMember]
        KeepOnRampRight,
        [EnumMember]
        KeepOnRampStraight,
        [EnumMember]
        KeepRight,
        [EnumMember]
        KeepStraight,
        [EnumMember]
        KeepToStayLeft,
        [EnumMember]
        KeepToStayRight,
        [EnumMember]
        KeepToStayStraight,
        [EnumMember]
        Merge,
        [EnumMember]
        None,
        [EnumMember]
        RampThenHighwayLeft,
        [EnumMember]
        RampThenHighwayRight,
        [EnumMember]
        RampThenHighwayStraight,
        [EnumMember]
        RoadNameChange,
        [EnumMember]
        Take,
        [EnumMember]
        TakeRampLeft,
        [EnumMember]
        TakeRampRight,
        [EnumMember]
        TakeRampStraight,
        [EnumMember]
        TakeTransit,
        [EnumMember]
        Transfer,
        [EnumMember]
        TransitArrive,
        [EnumMember]
        TransitDepart,
        [EnumMember]
        TurnBack,
        [EnumMember]
        TurnLeft,
        [EnumMember]
        TurnLeftThenBearLeft,
        [EnumMember]
        TurnLeftThenBearRight,
        [EnumMember]
        TurnLeftThenTurnLeft,
        [EnumMember]
        TurnLeftThenTurnRight,
        [EnumMember]
        TurnRight,
        [EnumMember]
        TurnRightThenBearLeft,
        [EnumMember]
        TurnRightThenBearRight,
        [EnumMember]
        TurnRightThenTurnLeft,
        [EnumMember]
        TurnRightThenTurnRight,
        [EnumMember]
        TurnThenMerge,
        [EnumMember]
        TurnToStayLeft,
        [EnumMember]
        TurnToStayRight,
        [EnumMember]
        Unknown,
        [EnumMember]
        UTurn,
        [EnumMember]
        Wait,
        [EnumMember]
        Walk
    }
}