//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitWP7.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransitWP7.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to go?.
        /// </summary>
        public static string ErrorMsgDescEndPointNotSet {
            get {
                return ResourceManager.GetString("ErrorMsgDescEndPointNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorMsgDescLocationNotFound {
            get {
                return ResourceManager.GetString("ErrorMsgDescLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality will be reduced until the location services are enabled. To turn them on, go to location settings on your phone settings..
        /// </summary>
        public static string ErrorMsgDescLocationServicesOff {
            get {
                return ResourceManager.GetString("ErrorMsgDescLocationServicesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection is required for finding new transit routes..
        /// </summary>
        public static string ErrorMsgDescNoNetwork {
            get {
                return ResourceManager.GetString("ErrorMsgDescNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorMsgDescNoTransitFound {
            get {
                return ResourceManager.GetString("ErrorMsgDescNoTransitFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you starting from?.
        /// </summary>
        public static string ErrorMsgDescStartPointNotSet {
            get {
                return ResourceManager.GetString("ErrorMsgDescStartPointNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With location services enabled, your current position must be known to get transit information..
        /// </summary>
        public static string ErrorMsgDescUnknownLocation {
            get {
                return ResourceManager.GetString("ErrorMsgDescUnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point not set.
        /// </summary>
        public static string ErrorMsgTitleEndPointNotSet {
            get {
                return ResourceManager.GetString("ErrorMsgTitleEndPointNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found.
        /// </summary>
        public static string ErrorMsgTitleLocationNotFound {
            get {
                return ResourceManager.GetString("ErrorMsgTitleLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are off.
        /// </summary>
        public static string ErrorMsgTitleLocationServicesOff {
            get {
                return ResourceManager.GetString("ErrorMsgTitleLocationServicesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network is available.
        /// </summary>
        public static string ErrorMsgTitleNoNetwork {
            get {
                return ResourceManager.GetString("ErrorMsgTitleNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transit found.
        /// </summary>
        public static string ErrorMsgTitleNoTransitFound {
            get {
                return ResourceManager.GetString("ErrorMsgTitleNoTransitFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point not set.
        /// </summary>
        public static string ErrorMsgTitleStartPointNotSet {
            get {
                return ResourceManager.GetString("ErrorMsgTitleStartPointNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location is unknown.
        /// </summary>
        public static string ErrorMsgTitleUnknownLocation {
            get {
                return ResourceManager.GetString("ErrorMsgTitleUnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitive uses your location to obtain more accurate local business information. It also uses this information to display your location on screen.
        ///Your location information is only sent to Bing Maps Search to find local businesses and calculate transit routes.
        ///
        ///Select OK to use location services.
        ///Select Cancel to not share your location.
        ///
        ///You can change your preferences in the settings page..
        /// </summary>
        public static string FirstRunAuthorizeLocationDesc {
            get {
                return ResourceManager.GetString("FirstRunAuthorizeLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Transitive to use location services?.
        /// </summary>
        public static string FirstRunAuthorizeLocationTitle {
            get {
                return ResourceManager.GetString("FirstRunAuthorizeLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crash occurred the last time you ran Transitive. Would you like to send an email to report it?.
        /// </summary>
        public static string LittleWatsonDialogDesc {
            get {
                return ResourceManager.GetString("LittleWatsonDialogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Report.
        /// </summary>
        public static string LittleWatsonDialogTitle {
            get {
                return ResourceManager.GetString("LittleWatsonDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My location.
        /// </summary>
        public static string MyCurrentLocationText {
            get {
                return ResourceManager.GetString("MyCurrentLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring your current location....
        /// </summary>
        public static string ProgressBarAcquiringLocation {
            get {
                return ResourceManager.GetString("ProgressBarAcquiringLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving endpoints....
        /// </summary>
        public static string ProgressBarSearchingEndpoint {
            get {
                return ResourceManager.GetString("ProgressBarSearchingEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching transit trips....
        /// </summary>
        public static string ProgressBarSearchingTrips {
            get {
                return ResourceManager.GetString("ProgressBarSearchingTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable location services to help find more relevant local business information.
        ///                       
        ///If location services are turned off, Transitive uses the center of the current map view to search for local business info..
        /// </summary>
        public static string ViewSettingsSetting1HelpText {
            get {
                return ResourceManager.GetString("ViewSettingsSetting1HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use location services.
        /// </summary>
        public static string ViewSettingsSetting1Title {
            get {
                return ResourceManager.GetString("ViewSettingsSetting1Title", resourceCulture);
            }
        }
    }
}
